title: Vicente's Blogs
author: vicente-s
email: vicenteajr.soriano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vicente's blogs. Here you'll find content about my experiences as a full stack developer and as a
  skateboarder too!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
